Include symfony
banovo/coding-standards pull request #12
Opened 2017-09-12 16:42 UTC by razbakov

Blocked by #10 #11 

- include symfony ruleset in repository
- update dependencies
- exclude rule MemberVarContainsNumbers

2017-09-13 07:01 UTC, eFzvai requested changes
The ticket [ch640]() required the coding style check binary for php7. But this pull request only add fix some test. 
This pull request can not close the ticket [ch640]

2017-09-13 07:38 UTC, razbakov commented
This branch is based on version 0.1.*, it includes bin/checker. That was a requirement. We used branch 0.2.* for php7 apps. The problem was dependencies in composer. I solved it by adding Symfony ruleset to thia repository and by excluding dependencies we don't need now. 

This version works good on coma and orocrm.

2017-09-13 07:40 UTC, eFzvai commented
Ok, but why this information is not in the commit message?

2017-09-13 07:43 UTC, eFzvai requested changes

2017-09-13 07:43 UTC, eFzvai commented on README.md
> +    "banovo/coding-standard": "0.1.*"
`0.3.*`

2017-09-13 08:25 UTC, razbakov commented on README.md
> +    "banovo/coding-standard": "0.1.*"
fixed

2017-09-13 08:25 UTC, razbakov commented
Updated PR description, which will be used as commit message.

2017-09-13 11:29 UTC, eFzvai submitted a review, later dismissed

2017-09-14 11:33 UTC, eFzvai approved these changes

2017-09-15 11:36 UTC, closed without merging

2017-09-15 11:39 UTC, razbakov commented
Recreated #16