Remove js checks
banovo/coding-standards pull request #25
Opened 2018-11-06 13:46 UTC by razbakov

2018-11-06 13:48 UTC, razbakov commented
[ch4189]

2018-11-12 08:21 UTC, eFzvai requested changes
Why did you remove the tests? Was there no other solution how to install the package that was noted?

The pull request unfortunately causes more questions than answers.

2018-11-12 08:37 UTC, razbakov commented
In evolution we have anothet version and configuration of eslint, in crm is different. The only way to run eslint is to run it separately for each project/config. And we can leave bin/checker only for php checks.

2018-11-23 13:34 UTC, eFzvai approved these changes

2018-12-03 13:36 UTC, merged